import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="row">
        <div className="col">
          <h1 className="display-1 text-center py-5">Home Page</h1>
          <Image src="/images/default.jpg" alt="img" width={500} height={300} />
        </div>
      </div>
    </div>
  );
};

export default Home;
